module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "𝐃𝐢𝐧𝐮 𝐏𝐫𝐨𝐝𝐮𝐜𝐭𝐢𝐨𝐧",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "true",
  "MODE": "private",
  "BOT_NUMBER": "94760177471",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": true,
  "DELETEMSGSENDTO": "94742274855",
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "true",
  "OWNER_NAME": "𝐃𝐢𝐧𝐮 𝐏𝐫𝐨𝐝𝐮𝐜𝐭𝐢𝐨𝐧",
  "OWNER_NUMBER": "94760177471",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "true",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
  "AI_MODE": false,
};
